### ISSUE TITLE
Locator functionality lacks 'please wait' feedback for the user

### ISSUE THREAD

**Issue by MarcelCutts** [katebee/jitsu-me#3]
One the main page of the application, the large 'Jitsu-Me!' button will attempt to
1. Seek permission for location lookup 
2. Place a pin on the map of its best guess of your current location.

The second step has taken, locally, up to 5 seconds. I imagine this number would increase on devices and connections that are slower than mine.

During this time, the user will not know whether it's 'doing anything' or 'working'.

How to deal with this is a matter of UX and aesthetic preference, but the standard seems to be some sort of spinny-wheel-like animation and a disabling of the pushed button to prevent repeat requests queuing up.

**Comment by katebee** [comment]
Fixed by commit 1a762fb
Loading wheels have been added to the mouse cursor and button while fetching the user location.
